apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-tjenester
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-tjenester-secrets
  image: {{version}}
  port: 7700
  liveness:
    path: /tms-min-side-tjenester/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-tjenester/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-min-side-tjenester/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://person.intern.nav.no/tms-min-side-tjenester"
    - "https://www.nav.no/tms-min-side-tjenester"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
